Features/c16 lidar support
lsd-maddrive/tigra-project pull request #120
Opened 2023-04-10 13:48 UTC by lasauveetgarde

добавлены поддержка двух 3д-лидаров

2023-04-15 14:25 UTC, KaiL4eK requested changes

2023-04-15 14:25 UTC, KaiL4eK commented on scripts/build.sh
> +    -j8 \
не проще будет `-j$(nproc)`? Ну или другой способ указания по кол-ву ядер в системе?
Просто так очень сильно замедлит на 4х ядерных системах

2023-04-15 14:25 UTC, KaiL4eK commented on tigra_vision/launch/drivers/start_lslidar_c16.launch
> +  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find tigra_vision)/rviz/check_c16_lidar.rviz" output="screen"/>
в драйвере всегда стартует rviz? Его тогда нельзя импортить в другие(

2023-04-15 14:25 UTC, KaiL4eK commented on tigra_vision/launch/drivers/start_lslidar_ch64w.launch
> +  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find tigra_vision)/rviz/check_ch64w_lidar.rviz" output="screen"/>
Тоже самое

2023-04-19 12:31 UTC, Alakeyska commented on scripts/build.sh
> +    -j8 \
Указание ядер сделано по причине зависания компа на многих машинах при сборке ртабмапа, поэтому надо оставить какое-то количество ядер свободными. Предлагаю сделать `-j$(($(nproc)-2)))`

2023-06-14 21:00 UTC, KaiL4eK approved these changes

2023-06-14 21:05 UTC, merged