Feature/gazebo model
lsd-maddrive/tigra-project pull request #57
Opened 2021-03-08 09:40 UTC by maryrosened

2021-03-11 18:11 UTC, KaiL4eK requested changes

2021-03-11 18:11 UTC, KaiL4eK commented on tigra_description/launch/gmapping.launch
> +  <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
Надо публиковать из лаунча модели

2021-03-11 18:11 UTC, KaiL4eK commented on tigra_description/launch/gmapping.launch
> +<?xml version="1.0"?>
Этот и другие файлы уже не относятся к описанию - это основной функционал робота, лучше создать отдельный пакет и там размещать скрипты и остальное

2021-03-11 18:11 UTC, KaiL4eK commented on tigra_description/launch/robot.launch
> +<node name="robot_state_publisher" pkg="robot_state_publisher" type="state_publisher"/>
А тут уже публикуется..)

2021-03-11 18:11 UTC, KaiL4eK commented on tigra_description/urdf/springrobot.urdf.xacro
> +  <gazebo reference="lidar_link">
Стоит все таки разделить создание модели на файлы:

- файл основной модели
- файл модели с лидаром
Так исключается дублирование кода + проще организовывать код

+ хорошо бы вынести колеса аналогично в отдельный файл

2021-03-31 17:40 UTC, adhelll commented on spring_simple_sample/urdf/simple.urdf.xacro
> +				<box size="1 1 0.1" />
почему тут через значения, а в инерции через xacro?

2021-03-31 17:41 UTC, adhelll commented on spring_simple_sample/urdf/simple.urdf.xacro
> +				<box size="1 1 0.1" />
как и в 41 строчке

2021-03-31 17:47 UTC, adhelll reviewed
.

2021-04-02 23:16 UTC, remontobuvi commented on tigra_description/urdf/robot.urdf.xacro
> +	<xacro:steer_wheel name="joint_right_wheel_1" base_name="base_link" xyz="0.5 -0.375 -0.35" />
положение xyz джоинтов все-таки стоит написать через ксакро

2021-04-02 23:21 UTC, remontobuvi requested changes
Не критично, но потом будет удобнее

2021-04-10 10:23 UTC, KaiL4eK approved these changes

2021-04-10 10:23 UTC, merged